export type DashBoardType ={
    dtIni: Date | null,
    dtFin: Date | null,
    totalDinheiro: number,
    totalCredito: number,
    totalCartao: number,
    totalDebito: number,
    totalVale: number,
    faturamentoTotal: number,
    taxaTotal: number,
    descontoTotal: number,
    topDezProduto: Array<any>,
    faturamentoMez: Array<number>,
    faturamentoAnual: Array<number>,
}